{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{ include "ecr-kube-helper.labels" . | indent 4 }}
  name: {{ template "ecr-kube-helper.fullname" . }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - delete
      - post
      - update
{{- end -}}