{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{ include "ecr-kube-helper.labels" . | indent 4 }}
  name: {{ template "ecr-kube-helper.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "ecr-kube-helper.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "ecr-kube-helper.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}