{{- if (include "ecr-kube-helper.createSecret" .) }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{ include "ecr-kube-helper.labels" . | indent 4 }}
  name: {{ template "ecr-kube-helper.fullname" . }}
type: Opaque
data:
  aws.accessKeyId: {{ .Values.ecr.awsAccessKey | b64enc | quote }}
  aws.secretAccessKey: {{ .Values.ecr.awsSecretKey | b64enc | quote }}
{{- end -}}
