{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels: {{ include "ecr-kube-helper.labels" . | indent 4 }}
  name: {{ template "ecr-kube-helper.serviceAccountName" . }}
{{- end }}
